apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/govee2mqtt
  - ./govee-credentials.sops.yaml
configMapGenerator:
  - name: govee2mqtt-values
    namespace: flux-system
    files:
      - values.yaml=./values.yaml
