apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin-token
  namespace: headlamp-system
  annotations:
    kubernetes.io/service-account.name: "headlamp-system-headlamp"
type: kubernetes.io/service-account-token
