apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-assistant-repo
  namespace: flux-system
spec:
  interval: 1h
  url: http://pajikos.github.io/home-assistant-helm-chart/
