apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:gYxQQJl/wpHONPBc854NtD+gECOnFtUYz5bm+TxHZToXTqrQUJrdOjREAZVQzxVnV9d06ZhTWma9ni65Vk60Fvlk0/bYWbZqqga4R+wyiMyZJwP3lqHFXmCmAcCogeLWfTy1a7q8PEQwr+MBdato64o0vCbv+iUwUQ==,iv:ErnOU+3NYAn7XtO+AWQkef1Q4Bmr8OYyQmEF4Urc4AY=,tag:rGyzx5ElLYOOh05PVOyckw==,type:str]
sops:
    lastmodified: "2025-10-17T06:11:20Z"
    mac: ENC[AES256_GCM,data:JBdnuMsS5+CoXk4I962U7ubKM5ho8gIMtZLW2N1BOnD215hZDe+OuwcTD8416b+3JU4hCnFwOkE93Sh/d46qPEBTFLQ9IW6xk1G/LmrbvcUoN2nmBlhCN+/gYZlFO4fP0Yr/8Q7ZRhmB7nk5IjkJHKDKC7jkA31iofYudVr679A=,iv:vSBe5j/9lZl4Dm1nZTd8o8lnBNbt0WsokbeeRefGrBA=,tag:VSNMSvA7/0EAkV8Dy4n5tQ==,type:str]
    pgp:
        - created_at: "2025-10-17T06:11:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3cGL9xUmwxMARAA1xYfT0b1obN0SWiZo7Laqidn676k/kfLJvKAqlkj/M10
            /dwahdD8QTVq9XNufEFvt8GQyFqrMvU4PyOpTtxMeXSyvIuSiyjnCSH0c80kwa3O
            lJ7kll4gxVr/3Zght2aZvy7cplUIVDn0hfeIX5Zc2mRUytkV5ZLqGSG2zjdYDvPL
            JMOZQyUF+aZ6UJLJIDzEncEBhXXy04YkCBTlO0qqKRj2UTePKOe0KlxX0qE2WTv9
            bvCYICnHGXCsnnE2ibqVOFG0kkozIs/JqbTMr+6Z2MZzCNxGamHZKCxKul1TAks/
            aF0AA0HSJ3A63aBLk8sU9JkwXrOqvTtZYu98ErqMzeb09tFkT/1TcOt2uANVXdNY
            r1goYMnHoZycRrT6wNclknVLQ/XeTbH2fSSpeUwB2Pnb1VJM4l9duRnbeIfD2Ils
            Z8TZw7jvpW9dIYxqwoI2rz/8wv/csNJ6tzbHOCctDhZ26OzCzeBvPd69m986H0cA
            BZRnDTXpbIZitS4klgMtQOA+ujQGHmyQgx8OtzVh3663GvYwfW3DnqNPYirV8cKm
            HnZ6V1lfBk3J4KwWov7z028bx34w24eaK84bmzAFkj+D+E82sFaBwXJlNyUHR0AM
            0zieM5lb3qunF3EPZ4eDc5Z7r4RrMcG4wpl7Eptpxl2B0g5K5YFRvI0rG6qnPFrU
            aAEJAhATyS42S+OznEYR8XKK/j59LAoEhIBIKTKLL4oZzxTCXPVAtG7NbeSMnDdQ
            tVDKUFrQA/NFd2NeQe0Ddic0gt79CBi5ubej9UHU2C6hqb+SaWapabYnzXtEheWP
            2kRnHVxA5pVW
            =6TOc
            -----END PGP MESSAGE-----
          fp: A846E73A713180DC60FA2A722DADD3F1DC5D54EC
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
