apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/pihole
configMapGenerator:
  - name: pihole-values
    namespace: pihole-system
    files:
      - values.yaml=./values.yaml
