apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: "v1.19.2"
      sourceRef:
        kind: HelmRepository
        name: jetstack-repo
        namespace: flux-system
  targetNamespace: cert-manager-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    prometheus:
      enabled: false
