apiVersion: v1
kind: Secret
metadata:
    name: govee-credentials
    namespace: hass-system
type: Opaque
stringData:
    GOVEE_EMAIL: ENC[AES256_GCM,data:qgH6UD69+EPxhT7IjlQrdri7,iv:YpwKYbP6h8AxcFeorWcmYnkKmqSZHKp6hlELnJRyDCk=,tag:4tGqyHKXELg9FG/cJIql4w==,type:str]
    GOVEE_PASSWORD: ENC[AES256_GCM,data:0uaypFTSJkyRrx/nJbs=,iv:nC6cZHFDUB+wzCS7RPChydSiUE4vvtNzNLyxbus+E2s=,tag:OVZ1T4YT0lMEnJCgGmHkGg==,type:str]
    GOVEE_API_KEY: ENC[AES256_GCM,data:00XxWk7RCv/E2hxEki2rywRlEN0hsGZZQiH5akBI5EQEUjYY,iv:qmeZRQsWmjXqqVAXYhPWaVz0J4oxLLVLCs8HvMF9Hng=,tag:hvsBHXvLmLJUZI/TY72G6Q==,type:str]
sops:
    lastmodified: "2026-03-21T00:51:14Z"
    mac: ENC[AES256_GCM,data:LZjpvoxlf1dNXNpr29sMpmEQLvkmW3V+UYYmgwtIXOnUs3jJcjMuYjELDiuMziKYV6ZLQpDxeuFkqTtI0aDcUKHACFvCL5Z+Wn4RTYGOhjqNO77mRYxjoJN51Yi4/7qkgzYFyh1AHDrbVd9+rdjz3gclP6GvhndKyS+3hYw/Vog=,iv:b8EKIC5s7GUZx1OCaKU3iT29tJCBK9IPM189lKBo2hg=,tag:OdNbJWtd2cxGkYflbHKklw==,type:str]
    pgp:
        - created_at: "2026-03-20T22:39:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3cGL9xUmwxMARAAnZtX6joUcQeURn9kgO3jvfEcrCq/fXJHBZAZm913x0pz
            4aYwz9NRv+Y9yJrOeK/Y0STF3yPkdn0TNgUSJWdNeJiY8WzHb3xJZgb1BuaBlR3f
            pMW+DrmJ7PbU75VNcATpZJjev/+8O0UlAjU0x5204/BRnsi3NbD5pxdaIrP+h9TW
            cyA8UfE5QMvk+ks7Soo1nhjPc+Yk6JnZMOt4L0NXg9LhVB+Oe8O3fnt7OiGOWOHb
            c6E8ZLeo0vN/vYRoZ6JQLMsVeD+ygUgYv8kcAiJFnoAIsBQ4F7w/sceKkRj8VMlr
            EL7EL0MHhJMM0l4l5bfModBqBl2d8Z6kX4/8hmkac2WGChIBZaEBnAoJZSDkA4br
            R9jY6lxS9FTpViKoNA4a8XDJSkFwSnYWYteeihGrd1OSkxHPKPG+x/il267eYc2q
            CtHdhxAvAGHVdXi864JEnu2Qz/WOTbnNlDczGyCAOb2Cdxi5KhY8PdEXzPxopdZn
            08O2X6CIx9rxr04Ouv4xWHqx4WAC7xkyuTr1ztQp5Ea4rwZfBhtKIKh7x8f9hSVl
            KHXo0p/NYpXXa+oakrbLCU6/vybY6P84jpLw9/lZqCXiOl/cbtGYhVVHjeuMnwx4
            rdHiolNsPc5L1vLB6OggIqd97FlpRIhQhRHtz+ShiIJ9Vyu7FopGYtiZ5Ky/1jTU
            aAEJAhCgWDusXR98FQjgrXEbSJZMKwcsCnUeeubwiSG2c8di7t49FLW9GfuH1tZl
            so1mJQUKBt2jS9imIIU1n0FmMS9iA9cArF4QxXCtll9d0fSi1vh1YAWB1SRwcNRk
            uNsUCTHYPpzi
            =SSzw
            -----END PGP MESSAGE-----
          fp: A846E73A713180DC60FA2A722DADD3F1DC5D54EC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.11.0
