apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/matter-server
configMapGenerator:
  - name: matter-server-values
    namespace: flux-system
    files:
      - values.yaml=./values.yaml
