controllers:
  main:
    strategy: Recreate
    containers:
      main:
        image:
          repository: ghcr.io/dtavana/homelab-devpod
          tag: ubuntu-24.04
          pullPolicy: Always
        env:
          TZ: America/New_York
          PUBLIC_KEY_URL: https://github.com/dtavana.keys
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "4"
            memory: 8Gi
service:
  main:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerSourceRanges:
      - 10.5.5.0/24
      - 192.168.0.0/24
    ports:
      ssh:
        port: 2222
        targetPort: 2222
        protocol: TCP
persistence:
  config:
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 30Gi
    retain: true
    globalMounts:
      - path: /home/dev
