controllers:
  main:
    strategy: Recreate
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/openssh-server
          tag: latest
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: America/New_York
          USER_NAME: dev
          SUDO_ACCESS: "true"
          PASSWORD_ACCESS: "false"
          LOG_STDOUT: "true"
          PUBLIC_KEY_URL: https://github.com/dtavana.keys
          DOCKER_MODS: lscr.io/linuxserver/mods:universal-package-install
          INSTALL_PACKAGES: bash|build-base|curl|fd|git|go|jq|neovim|nodejs|npm|py3-pip|python3|ripgrep|tmux|unzip|wget|zip
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "4"
            memory: 8Gi
service:
  main:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerSourceRanges:
      - 10.5.5.0/24
      - 192.168.0.0/24
    ports:
      ssh:
        port: 2222
        targetPort: 2222
        protocol: TCP
persistence:
  config:
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 30Gi
    retain: true
    globalMounts:
      - path: /config
