controllers:
  main:
    containers:
      main:
        image:
          repository: henrygd/beszel
          tag: latest
        env:
          PORT: 8090
          TZ: "America/New_York"
  agent:
    type: daemonset
    hostNetwork: true
    containers:
      main:
        image:
          repository: henrygd/beszel-agent
          tag: latest
        env:
          KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEjWnqu98ZQU+E6z3Pa5h/+hRiF4pWvjUO9410eRBbXw"
          PORT: "45876"
service:
  main:
    controller: main
    ports:
      http:
        port: 8090
ingress:
  main:
    enabled: true
    className: "nginx-internal"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - host: "beszel.internal.dtavana.dev"
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: beszel-tls
        hosts:
          - beszel.internal.dtavana.dev
persistence:
  data:
    enabled: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: "2Gi"
    advancedMounts:
      main:
        main:
          - path: /beszel_data
