apiVersion: v1
kind: Secret
metadata:
    name: playit-secret
    namespace: minecraft-system
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:aRVwHerh/PXBIKUZlfrMvMiN1fSxJYckTmcvEH5Eq74I90zwd88228fGJa2N6AmK9p6vXHfpYu1v59Arw7S5Ng==,iv:dNO4CSVHvCRGdOYm8KFmPALLgNTt5VhqCv86jztqoU0=,tag:qu0I3rpKndz5zze4nNyBVQ==,type:str]
sops:
    lastmodified: "2026-04-19T03:59:24Z"
    mac: ENC[AES256_GCM,data:GJjpjcIzHfpDuqICq+oSaiuHzR98VZf3cHHBaOGlpj9MiP8X7iwv4Q5XwMVQNgxDh1QgDhjhzS9v7yiU4+EdyJdI+ZadHWBtNoVm57SQXcxjCOYDzaHq+OCfUXc2MU36fnbFO2fVsum4CIUilMbGxGESlOksjcSwIdWhVwN9lu4=,iv:48ZejN08RUytfQ0TNdS57jZpfCY33Um0KMrlb7Ggoaw=,tag:DvQ2Z2qmba48BJhHqNfEkA==,type:str]
    pgp:
        - created_at: "2026-04-19T03:59:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3cGL9xUmwxMAQ/+NGSWdrkTXLH43eqHnF/K6aTz60vWLTodulLMrgWDmBpw
            FoIFmRqqLYNZ6sToAjuPcil2BBMxqys7wrJdtJVNWOZiBrJvyt6GBPZuC9e7kaA9
            lhguN9BRe/uyxIV2h8PCECPFtC0CdG8pza+UiRfBG1fdUvZbnZdxUTn4PRDf4kZ6
            PkoHw0SQNDiLjoo9/AhlyLkNhqA6eyQmv+fHFybB+hsLdzC9CJ96lE6uIr7oA8be
            p2AhabQAhFlw0OPAjIYjy2eglS4eR7NFH42Ocx5RhfwrOdXQWXMyVxU8oLVOOpKl
            9siNZpB3OExmjNtZzVyTThHgW9+fJi6lhMWobwW7rtWr+riEf2FMk91YLXePZevo
            nl64mQK9lCdrbbx3vCa8PuERnL4+1j8Jdz2EQr4+U/a2hGGbiN5r4ctmVdsK9U8y
            g+Vvf1GyTQdZsWLYl68Cp55ILPweR29ZpThyrk7VeeJjQ+otYL7NY9r5K3J+e0xu
            FcjddsXZWpHbt62OYyQs31quVrQw7eYW9CFpLT9qa1XyWNTcKxM8FRlR23RQ/hk9
            DXe5tehWnpKlpviISVjepZLrRkcDJZM4kKppX0k3zbL1H1kHk7BhIr9FzKkXlADF
            luR24BZyiKztJZjBPoid/UkVcldfZ/Xm8GalkaOZWbhOxzdXDg+p6SymplcPMoDU
            aAEJAhDz5eaRR0YWAywQfqAuyADYq+rAOg5A+CwHQpiMmhqtUVeRgwE9KNlXrcIB
            zx4Zw5IX6e3CR2SC2g+puWfcEBkg4TdTuQkDbDjANQAasgpbl+WDIUUirhxxvp1E
            heh7AJmqTIN5
            =9tk6
            -----END PGP MESSAGE-----
          fp: A846E73A713180DC60FA2A722DADD3F1DC5D54EC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.11.0
