controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/itzg/minecraft-server
          tag: latest
        env:
          EULA: "TRUE"
          ENABLE_AUTOPAUSE: "TRUE"
          TYPE: "PAPER"
          MAX_MEMORY: "3G"
          PLUGINS: "https://github.com/playit-cloud/playit-minecraft-plugin/releases/latest/download/playit-minecraft-plugin.jar"
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            memory: 4Gi
service:
  main:
    controller: main
    type: ClusterIP
    ports:
      minecraft:
        port: 25565
        protocol: TCP
persistence:
  data:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /data
