public-resources:
  minecraft:
    name: Minecraft
    protocol: tcp
    proxy-port: 25565
    targets:
      - hostname: minecraft-system-minecraft.minecraft-system.svc.cluster.local
        port: 25565
