apiVersion: v1
kind: Secret
metadata:
    name: newt-main-tunnel-auth
    namespace: newt-system
type: Opaque
data:
    NEWT_ID: ENC[AES256_GCM,data:tTi1E4XH8EA6zkwixlF5ABpKIqY=,iv:Jf2xmFmhwrOEZLYu79NUZd3pUzDVQAkpEXdRaHnGXco=,tag:Z6W841C0IrDDiLvYsmNfcA==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:ZeGFirf2E3ZDYYNrU7UIFByyfY9TLc0qZYKkJY2H3ApYZSQ0s8XHGFinIOXQoTSUQYlVH5GstlNYe4H9B7WK6Q==,iv:8veN4JpDt+/4PKokn9fpX23qmBAJ1YYLHvuVUriF9/Q=,tag:QlfDtcQcSDGs8TiavYdRKQ==,type:str]
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:7LOWCibcGCBCsCdLrLLTOYNbDGASwwzGP3WkiFXfGMjL+3zlZnf7qA==,iv:lARhsgwA3uvP9WOwjFE7V3+qBQBrTkhsTLR9JHaHJxI=,tag:GOcklwO73ult0c9ze00A/w==,type:str]
sops:
    lastmodified: "2026-05-21T02:15:04Z"
    mac: ENC[AES256_GCM,data:C3bjKqTHa8dWRATeJfn/4zu4JhKhoXQB0p4FH57+pvBIWE0hNcjAM77vyzibZRSUcMg27ZnSdSpIpRCER1z0Gye9qtScUKbGlWEnmfmjjXlRq2mWgz+7Z6lozl9EWRxusTsdwZQmynyOI3EIfuqIGEwKrIbzkPhDNnIEAzCbo68=,iv:Y37yFBKqXEX+MRlH8H+mu/SwE5kg/b+F2gdXHNYBv6M=,tag:+lnxBRQfK0fxistWiJhWwg==,type:str]
    pgp:
        - created_at: "2026-05-21T02:15:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3cGL9xUmwxMAQ//cGhufs38JJz17MttRlbVqTMlnXfXvdCMtjGg90v2+2oG
            eZTg1pFd5Ow5plDs3iy+hoY/JzZmom6/f4M6L5g8QyiDVYqBYAzRRouve/rR0Xz1
            Ogiiv9QxhBFKCY9kD2LrB4DU9fpojUeWZ1tqzwcqWn9hCgBHYmGwUkg2/qOGsvJu
            OaJlFjRlsAKNfg63y5HjH77ShnN3AhbnDPGjfNSZ8nX9J3ObDtIoMiawIRE9AO17
            rj+WH+m0mNUywyR2F8EWe837H5Z/VuUQABKvRJD9T5U9iQwyjZHZ2ARO1WZkMytB
            QnQjpmRpt27xe6/fJvRxl2crcAFX26zVR00yzEDNvw7E5e/2cmny21HMgG4rO0ix
            xRwQqTBqYUXqjYEXmo4IprmRQX/hBqIGv4uvUKnrKLZPzO7aosTdd9YTfQ/13oVw
            GDWvmObcusqw55ZSpoHd4bvzD7vVIHDGQKo60kIz6/qh3o7ebqQKSf3ZlYNo5Thr
            Z39lUWDkgeoJ++IRpPlZ2oEjjw+3hL0ya/EuycvyJBZ0M2FeAKSo6sC9nAtWPPVn
            /YeXLxBheZPQdKIW5GfZMCpm/cCOjcZQoBUFIBv5DuGv34M7VYzwPhqWkd82rEne
            Uud1DXaXQ2b/rSc7bhtom0+kirMT36UxeTGGIdV9C9IkgieEo3ocMAwpY4NFgvjU
            aAEJAhBbPf1fJjJos3Vy52Ndv63jcD2aRKx1mkyFT7JQtw3dF9Z33Icw6jxCPEYK
            7SOinjWe+4IBp50hodV6IvXrilIf6zHaFQPr4zSWjuMTpHL2difjGCN+hh6zk+YF
            UvZcPn8IpR8c
            =Y2yy
            -----END PGP MESSAGE-----
          fp: A846E73A713180DC60FA2A722DADD3F1DC5D54EC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.11.0
