apiVersion: v1
kind: Secret
metadata:
    name: newt-main-tunnel-auth
    namespace: newt-system
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:olw8mGeEg+M7EFon7TK70Zhne7M43WYLmK4rQw==,iv:ElJ+rQT2RU/QNtNaIj5/P332JVFEbMzlwjEDsFjtj00=,tag:9K6FqGKAyHZW7flGbuhuSA==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:wPIhsMyw0Wxok0/Gde5B,iv:LJMr/nh2hXd2KhxP4GOMfv0+9kbZH8uFCJ2DAW6s/tw=,tag:DEj7w9ahc1XSPypU8gvU/w==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:f90/jOzC0qCSi7c6PcKX0Ul0DZC05HBXWWhdTAPNuUJPSWPqcrHekFxfbs1nPCZ0,iv:A9A+Nfn+CLUWAQOIPB/ZpxH+5slrO1x7Ny+fu4AtUK0=,tag:iZ30UlgLGEMuLv7ood8B6Q==,type:str]
sops:
    lastmodified: "2026-05-21T02:55:29Z"
    mac: ENC[AES256_GCM,data:mE5lS4NObZ9dgT6xbw3YieaGVffI7lC72CLuWRov85BGH8Zw4zuZxMBe0kD7DVwyaQU+iK4jc9GHc4UI3vS9lfxkxlYO1K91YmDT1DKY2oI/nogCovMrxirSBc03hCER5GBsQwWv0/SjS5BUiqvpYVS+IM6NWvwNOEPfCMfBJhA=,iv:tKO/jxZqusl6t460Uviu057yplTxh66eEP88hyKxh24=,tag:Ky6iSdnAfS02jAKyNwqYGw==,type:str]
    pgp:
        - created_at: "2026-05-21T02:55:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3cGL9xUmwxMARAAqOsr1isgAVxUFd4j6aENCTkledo70hsVbnlx5Ve1f9uD
            avfOvtFSiO/9Je8nLl0lMdujI54uq4HQQbvDWgXassFUlJ7VNM3wbJbP048xEXHv
            Ku26Wh3fSUc50zLm75+UsJXyPqziWE5RVMxI4yOzQWuR8WYz/aZB51cjP6k/GKTd
            2a7cykeMoj3RCQ59MyK66DPVLnokEevsjJ/mz0ZEBCkQS9jShyHbrQQG/S3CNjQi
            JqLHERtYVE65IExiPVxybs0hZFFjGTmkaCfcg3O7pIRlh0pJl9qg1DOf7dFrAPYd
            yHsRr+5uBhc1RQa93Yp2BkFa4/1BzQjjwzhvduRYlaBl39+kEEYH3ONKLQZZE5pk
            /Cy+PW+FzqNVzHSp4v0LuoJLAYCkjGNSyvv3OA7h53g3HCZSlLtbo9dT638sfvsd
            XVu7t7DPy//umbi7bPZA32mID9IYaRDfqFGQO27ihKUn6RtUqXy/rJsvzkagZjhr
            Jft/Mqs+NdltBRAaUip5J4a0SoyVJu4ayZrLjJOZ/d8e6dJtuBVc8RFHvBexBuCj
            UqGdnpnH1wItkcEuCa1gUTSDvBES3E09GAgFDtgcD4LIwJ5206j/Y8qvRJXVGXPB
            Krl/FnPJoENjIgDN2Cg6HxE7vEAnonkSJefuFXyOg9C4nSub9oNdeSUsu5Xo4eDU
            aAEJAhCwmZMzFFrXg/amf+RV+FVb4H3MB0ffNqJ7EYrJRp9sElZkSHbnVsm7e4XD
            SvYsEp0gJI5qU3YzX34TnkEq87QOzWFDFn+o2Rzixb/lc8v72vAm4CNAC+bxxt3L
            82mx7rA5w2wj
            =LLEz
            -----END PGP MESSAGE-----
          fp: A846E73A713180DC60FA2A722DADD3F1DC5D54EC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.11.0
