apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newt-main-tunnel-config
  namespace: newt-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
