apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/homepage
  - ingress.yaml
  - ingress-internal.yaml
configMapGenerator:
  - name: homepage-public-config
    namespace: homepage-system
    files:
      - bookmarks.yaml=./generated/public/bookmarks.yaml
      - custom.css=./generated/public/custom.css
      - custom.js=./generated/public/custom.js
      - docker.yaml=./generated/public/docker.yaml
      - kubernetes.yaml=./generated/public/kubernetes.yaml
      - proxmox.yaml=./generated/public/proxmox.yaml
      - services.yaml=./generated/public/services.yaml
      - settings.yaml=./generated/public/settings.yaml
      - widgets.yaml=./generated/public/widgets.yaml
  - name: homepage-internal-config
    namespace: homepage-system
    files:
      - bookmarks.yaml=./generated/internal/bookmarks.yaml
      - custom.css=./generated/internal/custom.css
      - custom.js=./generated/internal/custom.js
      - docker.yaml=./generated/internal/docker.yaml
      - kubernetes.yaml=./generated/internal/kubernetes.yaml
      - proxmox.yaml=./generated/internal/proxmox.yaml
      - services.yaml=./generated/internal/services.yaml
      - settings.yaml=./generated/internal/settings.yaml
      - widgets.yaml=./generated/internal/widgets.yaml
