apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portainer-system
resources:
  - namespace.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: portainer-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
