persistence:
  enabled: true
  storageClass: "longhorn"
  size: "2Gi"

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - host: "portainer.cube.local"
      paths:
        - path: /
          pathType: Prefix
