apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ihg12cdqPyGHlBynT7EOpPT4VA1F/z6ADHJbwzAfIm8ALjrKb462GoIPz/pawnKSkGzMqXnbm9dfRu6B/A==,iv:neftb5HZgey36LDpEC7kjDli97CZHuUK/FEdln7fLzg=,tag:3rHdwsbL7z4ajbMMsrNTEw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SzbuERY8DJbZbXx5BQSPGXjGLSbVwbClIG/L84lqUCceQBHszV/dWA==,iv:GbRBWMUAyjQdoVjCHrLdVCQLtzVDzfbw7IOVbEWeB3Q=,tag:by02L1VBOlVS3ctFSZ4ugQ==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:0pLhxUp8vxXyraz/Vc4E68m+u6bJO+kgnozxt6lo,iv:lpDNX0ZsPuFHG7K45IvIjtZ7ueg1WDmdwo10hSR4Xnw=,tag:T99tbkSvZYty5sr4xV1vuw==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:XgHNSal65JY=,iv:YF0mOHyZkS7rR4hirBzo9QM0hvV0PZyRYxL6/rzUfIY=,tag:M9saAxijPT22aSfvutR14g==,type:str]
sops:
  lastmodified: "2026-03-21T20:13:55Z"
  mac: ENC[AES256_GCM,data:WuGPbwyPE+leNyVom+vBRZdOyytkssz4ezzXFt4rHG+Q4mH2EDYYroS+/HeidJba+xkZU2Y/t8MEf5xZ9lLbvFBdLX+7rxrolpaM/X7qXlhuL5fuhrNS5FbizpkVHg9yYV7mXFsDwc+fNxz9iVjIlF7dLsC0E9/bm5dNXyxebmg=,iv:ZwrXwZPrTIcdLjCfnvoKamt9MXvZvbTFmaTZDx98JSE=,tag:pPe6rf8AdSQqc4gKGNCJ3Q==,type:str]
  pgp:
    - created_at: "2026-03-21T17:36:40Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3cGL9xUmwxMAQ/+JE4RRakyFqEERhTaddOqyszLQmkFg4HCC7GzabHxddbm
        mZvC5h12D7QiXXhjRCRFZukb20zkTO8d53rXyHwDKB2tZXBDUYbiSCAT1O/3DlMx
        0Xg2zYkpndJxtq0oQ5dTrvSSAZWO3iQm/BtfrJb3w+20LdnsRwL1D8XP7hxQmlZT
        KQJzln+IgjmR7wTg0tsUPLA6CDwiNbCsUiZSzXaBuPf5shK87Sfy2qEAI9iBoZFc
        IaLgwnUpAeMhZuLxHpu5Hwuw2lWp5nqQIcsH/cML4zagwVtTkD4gqltvsT6OHqib
        swJUP9PkzGvdGEuDwO+HdEak9n/NKwTHYYiBebCPFCdXghJwLKOEQe0RZnmdTn1m
        jNm8cwoAQaubi7S8JwH38eGR57ocMtXOhUPmlSRz8VkosJ/mQbUvuywkLoTZUVf/
        aR3qb9I2H2hBM6jNqV8R9GDd/924StAcpE+k06B1FwHSWSKDofjARt497EikB+uC
        FEZspLisSS5cdtAUsQDiboLFg06FB8MZGj4QXCF+VMiOkcHh6qTPyB9+IuFWc0P0
        I7FAYI9KCQMgIJ0Em2EzjP5YyYKvx3dOXwCtR//6Cicm+26+V51by0NJO/r+Tf/Q
        ZF777b/HlHsN2kf8mDZSpiX7vQKdJSzH7NM0UtNq0AujrL39Vt0Lo17ritSgSwPU
        ZgEJAhAif4EuIVUkFwzS3qbIBk2SBtLTF6oXRl1gcVkMIjjIM847u7oTObBYbXF/
        zgnzHH2MxXPV0EPebwbyzeF3Ss/1V4RAlAZ1gyAI9BPun9ZInxfuXzmciPqJohFB
        1UMqrzlhvg==
        =2Gfs
        -----END PGP MESSAGE-----
      fp: A846E73A713180DC60FA2A722DADD3F1DC5D54EC
  encrypted_regex: ^(data|stringData|email)$
  version: 3.11.0
