apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ihg12cdqPyGHlBynT7EOpPT4VA1F/z6ADHJbwzAfIm8ALjrKb462GoIPz/pawnKSkGzMqXnbm9dfRu6B/A==,iv:neftb5HZgey36LDpEC7kjDli97CZHuUK/FEdln7fLzg=,tag:3rHdwsbL7z4ajbMMsrNTEw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SzbuERY8DJbZbXx5BQSPGXjGLSbVwbClIG/L84lqUCceQBHszV/dWA==,iv:GbRBWMUAyjQdoVjCHrLdVCQLtzVDzfbw7IOVbEWeB3Q=,tag:by02L1VBOlVS3ctFSZ4ugQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:0pLhxUp8vxXyraz/Vc4E68m+u6bJO+kgnozxt6lo,iv:lpDNX0ZsPuFHG7K45IvIjtZ7ueg1WDmdwo10hSR4Xnw=,tag:T99tbkSvZYty5sr4xV1vuw==,type:str]
sops:
    lastmodified: "2026-03-21T17:36:40Z"
    mac: ENC[AES256_GCM,data:bD8343AYJ2slJYHqAvwaQA2ZEJMyGVgU4q61Fo0YwfTIEaJX9q5MXUz7XlDmbMpc3bXIWHEnWPYLuL2DX4jprGjrThUJvn5g8ASicgFvL/dNsH8Fy9k+54Ldi0BlWVS4QXfvFFETmfPcYY0Fe3065VHOVeeokUm5oDDM4X858KI=,iv:gqGAzFO5eRHCjzQOLYl+Zxt2yBJY9O1uWXQzIjtrWGM=,tag:3LRv5grEWavGmCnDNcD9WQ==,type:str]
    pgp:
        - created_at: "2026-03-21T17:36:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3cGL9xUmwxMAQ/+JE4RRakyFqEERhTaddOqyszLQmkFg4HCC7GzabHxddbm
            mZvC5h12D7QiXXhjRCRFZukb20zkTO8d53rXyHwDKB2tZXBDUYbiSCAT1O/3DlMx
            0Xg2zYkpndJxtq0oQ5dTrvSSAZWO3iQm/BtfrJb3w+20LdnsRwL1D8XP7hxQmlZT
            KQJzln+IgjmR7wTg0tsUPLA6CDwiNbCsUiZSzXaBuPf5shK87Sfy2qEAI9iBoZFc
            IaLgwnUpAeMhZuLxHpu5Hwuw2lWp5nqQIcsH/cML4zagwVtTkD4gqltvsT6OHqib
            swJUP9PkzGvdGEuDwO+HdEak9n/NKwTHYYiBebCPFCdXghJwLKOEQe0RZnmdTn1m
            jNm8cwoAQaubi7S8JwH38eGR57ocMtXOhUPmlSRz8VkosJ/mQbUvuywkLoTZUVf/
            aR3qb9I2H2hBM6jNqV8R9GDd/924StAcpE+k06B1FwHSWSKDofjARt497EikB+uC
            FEZspLisSS5cdtAUsQDiboLFg06FB8MZGj4QXCF+VMiOkcHh6qTPyB9+IuFWc0P0
            I7FAYI9KCQMgIJ0Em2EzjP5YyYKvx3dOXwCtR//6Cicm+26+V51by0NJO/r+Tf/Q
            ZF777b/HlHsN2kf8mDZSpiX7vQKdJSzH7NM0UtNq0AujrL39Vt0Lo17ritSgSwPU
            ZgEJAhAif4EuIVUkFwzS3qbIBk2SBtLTF6oXRl1gcVkMIjjIM847u7oTObBYbXF/
            zgnzHH2MxXPV0EPebwbyzeF3Ss/1V4RAlAZ1gyAI9BPun9ZInxfuXzmciPqJohFB
            1UMqrzlhvg==
            =2Gfs
            -----END PGP MESSAGE-----
          fp: A846E73A713180DC60FA2A722DADD3F1DC5D54EC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.11.0
