defaultSettings:
  defaultDataPath: "/var/lib/longhorn/"
defaultBackupStore:
  backupTarget: "s3://dtavana-longhorn-backups@us-east1/"
  backupTargetCredentialSecret: "longhorn-backup-secret"
ingress:
  enabled: true
  ingressClassName: "nginx-internal"
  host: "longhorn.internal.dtavana.dev"
  path: /
  pathType: Prefix
  tls: true
  tlsSecret: longhorn-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
