apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole-system

resources:
  - namespace.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: pihole-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true