persistentVolumeClaim:
  enabled: true
  size: 2Gi
  storageClassName: longhorn

serviceWeb:
  type: LoadBalancer

serviceDns:
  type: LoadBalancer

capabilities:
  add:
    - NET_ADMIN

dnsmasq:
  customDnsEntries:
    - address=/cube.local/192.168.0.243
