persistentVolumeClaim:
  enabled: true
  size: 2Gi
  storageClassName: longhorn

serviceWeb:
  type: LoadBalancer

serviceDns:
  type: LoadBalancer

podDnsConfig:
  enabled: false

dnsmasq:
  enableCustomDnsMasq: true
  customDnsEntries:
    - address=/cube.local/192.168.0.33

capabilities:
  add:
    - NET_ADMIN
