persistentVolumeClaim:
  enabled: true
  size: 2Gi
  storageClassName: longhorn

serviceWeb:
  type: LoadBalancer

serviceDns:
  type: LoadBalancer

podDnsConfig:
  enabled: false

capabilities:
  add:
    - NET_ADMIN
