fullnameOverride: kube-prometheus-stack

grafana:
  enabled: true
  defaultDashboardsTimezone: America/New_York
  persistence:
    enabled: true
    size: 5Gi
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - grafana.internal.dtavana.dev
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.internal.dtavana.dev

alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - alertmanager.internal.dtavana.dev
    paths:
      - /
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.internal.dtavana.dev
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - prometheus.internal.dtavana.dev
    paths:
      - /
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.internal.dtavana.dev
  prometheusSpec:
    retention: 15d
    retentionSize: 18GB
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false
