apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: homepage-repo
        namespace: flux-system
      interval: 15m
  targetNamespace: homepage-system
  valuesFrom:
    - kind: ConfigMap
      name: homepage-values
