apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.35.0
      sourceRef:
        kind: HelmRepository
        name: pihole-repo
        namespace: flux-system
      interval: 1m
  targetNamespace: pihole-system
  valuesFrom:
    - kind: ConfigMap
      name: pihole-values