apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./home-assistant
  - ./ha-mcp
  - ./pihole
  - ./govee2mqtt
  - ./mqttx
  - ./matter-server
  - ./zigbee2mqtt
  - ./headlamp
  - ./beszel
  - ./minecraft
  - ./bambuddy
  - ./postgres
  - ./dbgate
  - ./homepage
