apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./home-assistant
  - ./pihole
  - ./govee2mqtt
  - ./mqttx
  - ./matter-server
  - ./zigbee2mqtt
  - ./headlamp
  - ./beszel
  - ./minecraft
