apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.13.3"
      sourceRef:
        kind: HelmRepository
        name: nginx-repo
        namespace: flux-system
  targetNamespace: nginx-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: nginx-values
  values:
    controller:
      service:
        type: LoadBalancer
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
