apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: hass-system
  labels:
    app: matter-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      containers:
        - name: matter-server
          image: ghcr.io/home-assistant/matter-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5580
              name: websocket
          volumeMounts:
            - name: config
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: matter-server-config
