apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: hass-system
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: "0.3.32"
      sourceRef:
        kind: HelmRepository
        name: home-assistant-repo
        namespace: flux-system
  targetNamespace: hass-system
  valuesFrom:
    - kind: ConfigMap
      name: home-assistant-values
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
