apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-config
  namespace: hass-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
