apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: hass-system
spec:
  selector:
    app: matter-server
  ports:
    - name: websocket
      port: 5580
      targetPort: 5580
      protocol: TCP
