apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  # CUSTOM
  - apps-kustomization.yaml
  - storage-kustomization.yaml
  - infra-kustomization.yaml
  - monitoring-kustomization.yaml
