apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra
  healthChecks:
    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Provider
      name: discord-provider
      namespace: flux-system
    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Alert
      name: discord-alert
      namespace: flux-system
