- Home:
    - Home Assistant:
        icon: home-assistant.png
        href: https://hass.dtavana.dev
        description: Home automation hub
        namespace: hass-system
        app: home-assistant
