persistence:
  enabled: true
  existingClaim: ""
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: "10Gi"

timezone: "America/New_York"

ingress:
  enabled: true
  ingressClassName: "traefik"
  hosts:
    - host: "hass.cube.local"
      paths:
        - path: /
          pathType: Prefix

configuration:
  enabled: true
  forceInit: false
  trusted_proxies:
    - "10.42.0.0/16"
    - "10.43.0.0/16"
