# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install yamllint
        shell: bash
        run: |
          pip install --user yamllint
      - name: Run yamllint
        shell: bash
        run: |
          yamllint --config-file .yamllint.yaml --format github .
  actionlint:
    name: GitHub Actions Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
